// remote/src/App.tsx
import React from "react";
import ReactDOM from "react-dom";

import { Counter  } from "./Counter";

import "./index.scss";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: remote</div>
    <Counter />
  </div>
);
ReactDOM.render(<App />, document.getElementById("app"));

// svelte-mf-app/originjs-plugin/host/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";

  let el;
  let Component;
  let Module;

  onMount(async () => {
    Module = (await import("remote/Counter")).default;
    Component = new Module({ target: el, props: $$props });
  });

  $: {
    if (Component) {
      Component.$set($$props);
    }
  }
</script>

<div class="mt-10 text-3xl mx-auto max-w-6xl">
  <div>Name: host</div>
  <div bind:this={el}></div>
</div>
