// react-mf-app/remote/src/App.tsx
import React from 'react';
import { createRoot } from 'react-dom/client';

import { Counter  } from './Counter';

import './index.scss';

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: remote</div>
    <Counter />
  </div>
);

const root = createRoot(document.getElementById('app') as HTMLElement);
root.render(<App />);

// angular-mf-app/remote/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CounterComponent } from "./modules/counter/counter.component";

@Component({
    selector: 'app-root',
    standalone: true,
    templateUrl: './app.component.html',
    styleUrl: './app.component.scss',
    imports: [RouterOutlet, CounterComponent]
})
export class AppComponent {
  title = 'remote';
}

<div class="mt-10 text-3xl mx-auto max-w-6xl">
  <div>Name: remote</div>
  <app-counter></app-counter>
</div>
