// svelte-mf-app/originjs-plugin/remote/src/lib/Counter.svelte
<script lang="ts">
  let count: number = 0
  const increment = () => {
    count += 1
  }
</script>

<div class="w-fit border-2 border-red-500 border-dashed rounded-lg p-2">
  <div>count = {count}</div>
  <button class="rounded-full bg-green-500 text-white p-2" on:click={increment}>add one</button>
</div>

// vue-mf-app/remote/src/components/Counter.vue
<script setup lang="ts">
  import { ref } from 'vue'

  const count = ref(0)

  const increment = () => {
    count.value++
  }
</script>

<template>
  <div class="w-fit border-2 border-red-500 border-dashed rounded-lg p-2">
    <div>count = {{ count }}</div>
    <button class="rounded-full bg-green-500 text-white p-2" @click="increment()">add one</button>
  </div>
</template>
