// single-spa/mfa1/src/components/Counter.tsx
import { useState } from "react";

export function Counter() {
  const [count, setCount] = useState(0);

  return (
    <div className="w-fit border-2 border-red-500 border-dashed rounded-lg p-2">
      <div>count = {count}</div>
      <button
        className="rounded-full bg-green-500 text-white p-2"
        onClick={() => setCount(count + 1)}
      >
        Add one{" "}
      </button>
    </div>
  );
}

// svelte-mf-app/originjs-plugin/remote/src/lib/Counter.svelte
<script lang="ts">
  let count: number = 0
  const increment = () => {
    count += 1
  }
</script>

<div class="w-fit border-2 border-red-500 border-dashed rounded-lg p-2">
  <div>count = {count}</div>
  <button class="rounded-full bg-green-500 text-white p-2" on:click={increment}>add one</button>
</div>
