// react-mf-app/remote/src/Counter.tsx
import { useState } from 'react';
import React from 'react';

export function Counter() {
    const [count, setCount] = useState(0);

    return (
        <>
            <div>count = {count}</div>
            <button className="rounded-full bg-green-500 text-white p-2" onClick={() => setCount(count + 1)}>Add one </button>
        </>
    );
}

// angular-mf-app/remote/src/app/modules/counter/counter.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-counter',
  standalone: true,
  imports: [],
  template: `
    <div>{{ counter }}</div>
    <button class="rounded-full bg-green-500 text-white p-2" (click)="increaseCounter()">Add one </button>
  `,
})
export class CounterComponent {
  counter = 0;

  increaseCounter(): void {
    this.counter++;
  }
}
